### ISSUE TITLE
Websocket issue. React web app. 

### ISSUE THREAD

**Issue by huwprosser** [chatr/chatra#3]
Getting a continuous 'web-socket disconnected' and 'page not found' loop whenever the widget loads.  Specifically error 404.

**Comment by vrizo** [comment]
> Getting a continuous 'web-socket disconnected' and 'page not found' loop whenever the widget loads. Specifically error 404.

Hi, @huwprosser! Can you please provide console and network logs from the Developer Tools? Also, have you tried to load the widget directly?

**Comment by huwprosser** [comment]
This issue has now resolved itself but seems to be affected by certain public WiFi networks when self hosting a site for development.  Thank you for your quick reply - and sorry to bother you!

**Comment by vrizo** [comment]
Glad to hear that it works now :)
